/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum15052026;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FormNilai extends javax.swing.JFrame {

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtKelas = new javax.swing.JLabel();
        txtMatkul = new javax.swing.JLabel();
        txtTugas = new javax.swing.JLabel();
        txtQuiz = new javax.swing.JLabel();
        txtUTS = new javax.swing.JLabel();
        txtUAS = new javax.swing.JLabel();
        editNama = new javax.swing.JTextField();
        editKelas = new javax.swing.JTextField();
        editMatkul = new javax.swing.JTextField();
        editTugas = new javax.swing.JTextField();
        editQuiz = new javax.swing.JTextField();
        editUTS = new javax.swing.JTextField();
        editUAS = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        txtNa = new javax.swing.JLabel();
        txtKonversial = new javax.swing.JLabel();
        editNa = new javax.swing.JTextField();
        editKonversial = new javax.swing.JTextField();

        jTextField7.setText("jTextField7");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM PENILAIAN MAHASISWA");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNama.setText("Nama Mahasiswa");

        txtKelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtKelas.setText("Kelas");

        txtMatkul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMatkul.setText("Mata Kuliah");

        txtTugas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTugas.setText("Nilai Tugas");

        txtQuiz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtQuiz.setText("Nilai Quiz");

        txtUTS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUTS.setText("Nilai UTS");

        txtUAS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUAS.setText("Nilai UAS");

        editNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNamaActionPerformed(evt);
            }
        });

        editKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKelasActionPerformed(evt);
            }
        });

        editMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMatkulActionPerformed(evt);
            }
        });

        editQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editQuizActionPerformed(evt);
            }
        });

        btnProses.setText("PROSES");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        txtNa.setText("Nilai Akhir");

        txtKonversial.setText("Nilai Konversial");

        editNa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNaActionPerformed(evt);
            }
        });

        editKonversial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editKonversialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(332, 332, 332))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(txtMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtKelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editQuiz)
                    .addComponent(editUTS)
                    .addComponent(editNama, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(editKelas)
                    .addComponent(editMatkul)
                    .addComponent(editTugas)
                    .addComponent(editUAS))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProses)
                        .addGap(211, 211, 211))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKonversial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(editKonversial, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(editNa))
                        .addContainerGap(119, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama)
                    .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKelas)
                    .addComponent(editKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatkul)
                            .addComponent(editMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProses))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTugas)
                            .addComponent(editTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNa)
                            .addComponent(editNa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuiz)
                            .addComponent(editQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKonversial)
                            .addComponent(editKonversial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUTS)
                    .addComponent(editUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUAS)
                    .addComponent(editUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNamaActionPerformed

    private void editKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editKelasActionPerformed

    private void editMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMatkulActionPerformed

    private void editQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editQuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editQuizActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        String nama = editNama.getText();
        String kelas = editKelas.getText();
        String matkul = editMatkul.getText();
        
        if (nama.isEmpty()|| kelas.isEmpty()|| matkul.isEmpty()){
            JOptionPane.showMessageDialog(this, "semua harus diisi","peringatan",JOptionPane.WARNING_MESSAGE);
        }
        
        try{
            double tugas = validasiNilai(editTugas.getText(),"Tugas");
            double quiz = validasiNilai(editQuiz.getText(),"Quiz");
            double uts = validasiNilai(editUTS.getText(),"UTS");
            double uas = validasiNilai(editUAS.getText(),"UAS");
            
            double na = 0.15*tugas + 0.2*quiz + 0.3*uts + 0.35*uas;
            
            editNa.setText(Double.toString(na));
            
            String hasilKonversi = konversiNilai(na);
            editKonversial.setText(hasilKonversi);
            
        JOptionPane.showMessageDialog(this, "nama : "+nama+
                                            "\nKelas : "+matkul+
                                            "\nNilaiAkhir : "+na+
                                            "\nhasil penilaian"+JOptionPane.INFORMATION_MESSAGE);
        }catch (Exception e){
                 JOptionPane.showMessageDialog(this, e.getMessage(), "validasi nilai",JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnProsesActionPerformed

    private Double validasiNilai(String input, String jenisNilai)throws Exception{
        double nilai = Double.parseDouble(input);
        if (nilai <0 || nilai >100 )
            throw new Exception (jenisNilai + "harus di antara 0-100");
        return nilai;
    }

    private String konversiNilai (double nilai){
        if (nilai >=80){
            return "A";
        }else if (nilai <80 && nilai >=65){
            return "B";
        }else if (nilai <65 && nilai >=55){
            return "C";
        }else {
            return "D";
        }
    }

    private void editNaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNaActionPerformed

    private void editKonversialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editKonversialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editKonversialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JTextField editKelas;
    private javax.swing.JTextField editKonversial;
    private javax.swing.JTextField editMatkul;
    private javax.swing.JTextField editNa;
    private javax.swing.JTextField editNama;
    private javax.swing.JTextField editQuiz;
    private javax.swing.JTextField editTugas;
    private javax.swing.JTextField editUAS;
    private javax.swing.JTextField editUTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel txtKelas;
    private javax.swing.JLabel txtKonversial;
    private javax.swing.JLabel txtMatkul;
    private javax.swing.JLabel txtNa;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtQuiz;
    private javax.swing.JLabel txtTugas;
    private javax.swing.JLabel txtUAS;
    private javax.swing.JLabel txtUTS;
    // End of variables declaration//GEN-END:variables
}
