/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum22062026;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FormTiket extends javax.swing.JFrame {

    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
        initComponents();
        txtHarga.setEditable(false);
        txtTotal.setEditable(false);
        txtDiskon.setEditable(false);
        txtBayar.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupTujuan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtTujuan = new javax.swing.JLabel();
        txtKelas = new javax.swing.JLabel();
        rbBkt = new javax.swing.JRadioButton();
        rbSolok = new javax.swing.JRadioButton();
        rbPar = new javax.swing.JRadioButton();
        cbKelas = new javax.swing.JComboBox<>();
        btnHarga = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        lblJml = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        lblTotHarga = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblBayar = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtDiskon = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDibayarkan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnHitUang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM PEMBELIAN TIKET BUS NUSANTARA");

        txtTujuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTujuan.setText("Tujuan");

        txtKelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtKelas.setText("Kelas");

        btnGrupTujuan.add(rbBkt);
        rbBkt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbBkt.setText("Bukittinggi");
        rbBkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBktActionPerformed(evt);
            }
        });

        btnGrupTujuan.add(rbSolok);
        rbSolok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbSolok.setText("Solok");

        btnGrupTujuan.add(rbPar);
        rbPar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbPar.setText("Pariaman");

        cbKelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilihan Kelas", "Ekonomi", "Bisnis", "Eksekutif" }));

        btnHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHarga.setText("Harga 1 Tiket");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        lblJml.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblJml.setText("Masukkan Jumlah Tiket");

        txtJumlah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTotHarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotHarga.setText("Total Harga");

        lblDiskon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDiskon.setText("Diskon");

        lblBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBayar.setText("Total Pembayaran");

        btnHitung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnKeluar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jLabel2.setText("Uang Dibayar");

        txtDibayarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDibayarkanActionPerformed(evt);
            }
        });

        btnHitUang.setText("Hitung Uang");
        btnHitUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitUangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblJml, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHitung)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBayar)
                                .addGap(18, 18, 18)
                                .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbSolok)
                                    .addComponent(rbBkt)
                                    .addComponent(rbPar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDiskon)
                                .addGap(88, 88, 88)
                                .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHitUang)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHarga)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotHarga)
                        .addGap(59, 59, 59)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtDibayarkan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(34, 34, 34)
                        .addComponent(btnKeluar)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(267, 267, 267))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBkt)
                    .addComponent(txtTujuan)
                    .addComponent(txtKelas)
                    .addComponent(cbKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(rbSolok)
                .addGap(18, 18, 18)
                .addComponent(rbPar)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJml))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotHarga)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtDibayarkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHitUang))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiskon)
                    .addComponent(jLabel3))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBayar)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnHitung)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnReset))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBktActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        int kelas = (int)cbKelas.getSelectedIndex();
        
        if(!rbBkt.isSelected()&&!rbSolok.isSelected()&&!rbPar.isSelected())
            JOptionPane.showMessageDialog(this,"Tujuan Belum Dipilih","Pesan Kesalahan",JOptionPane.ERROR_MESSAGE);
        else if(cbKelas.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Kelas Belum dipilih","Pesan Kesalahan",JOptionPane.ERROR_MESSAGE);
        }
        else{
        switch (kelas){
            case 1 : if(rbBkt.isSelected())
                        txtHarga.setText("25000");
                     else if(rbSolok.isSelected())
                        txtHarga.setText("20000");
                     else
                        txtHarga.setText("15000");
                     break;
            case 2 : if(rbBkt.isSelected())
                        txtHarga.setText("50000");
                     else if(rbSolok.isSelected())
                        txtHarga.setText("40000");
                     else
                        txtHarga.setText("30000");
                     break;   
            case 3 : if(rbBkt.isSelected())
                        txtHarga.setText("15000");
                     else if(rbSolok.isSelected())
                        txtHarga.setText("30000");
                     else
                        txtHarga.setText("55000");
                     break;        
            }
        }
    }//GEN-LAST:event_btnHargaActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try{
        int jumlah = Integer.parseInt(txtJumlah.getText());
        if(jumlah<=0){
            JOptionPane.showMessageDialog(this,"Jumlah tiket harus lebih dari 0","tidak boleh nol",JOptionPane.ERROR_MESSAGE);
        }else{
            double harga = Double.parseDouble(txtHarga.getText());
            double total = jumlah * harga;
            double diskon = 0;
                if(jumlah>5)
                    diskon = 0.1*total;
            double bayar = total-diskon;
        
        txtTotal.setText(Double.toString(total));
        txtDiskon.setText(Double.toString(diskon));
        txtBayar.setText(Double.toString(bayar));
             }
        
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"Jumlah harus angka bilangan bulat","Pesan Error",JOptionPane.ERROR_MESSAGE);
            txtJumlah.setText("");
            txtJumlah.requestFocus();}
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtHarga.setText("");
        txtJumlah.setText("");
        txtTotal.setText("");
        txtDiskon.setText("");
        txtBayar.setText("");
        txtDibayarkan.setText("");
        
        cbKelas.setSelectedIndex(0);
        btnGrupTujuan.clearSelection();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "Apakah ingin keluar?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        
        if(pil==JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtDibayarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDibayarkanActionPerformed
        
    }//GEN-LAST:event_txtDibayarkanActionPerformed

    private void btnHitUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitUangActionPerformed
    double totalBayar = Double.parseDouble(txtBayar.getText());
        double uang = Double.parseDouble(txtDibayarkan.getText());

        if (uang < totalBayar) {
            double kurang = totalBayar - uang;
            JOptionPane.showMessageDialog(this,"Uang Anda Kurang Rp. " + kurang,"Pembayaran Gagal",JOptionPane.WARNING_MESSAGE);

        } else {
            double kembalian = uang - totalBayar;
            JOptionPane.showMessageDialog(this,"Pembayaran Berhasil\nKembalian Anda Rp. " + kembalian,"Pembayaran Sukses",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnHitUangActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupTujuan;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHitUang;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblBayar;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblJml;
    private javax.swing.JLabel lblTotHarga;
    private javax.swing.JRadioButton rbBkt;
    private javax.swing.JRadioButton rbPar;
    private javax.swing.JRadioButton rbSolok;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtDibayarkan;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JLabel txtKelas;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtTujuan;
    // End of variables declaration//GEN-END:variables
}
