/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum29062026;

/**
 *
 * @author USER
 */
public class FormMinuman extends javax.swing.JFrame {

    private FormUtama utama;
    
    public FormMinuman() {
        initComponents();
    }
    
    public FormMinuman(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ckbKopiSusu = new javax.swing.JCheckBox();
        ckbMilo = new javax.swing.JCheckBox();
        ckbTeh = new javax.swing.JCheckBox();
        txtKopiSusu = new javax.swing.JTextField();
        txtMilo = new javax.swing.JTextField();
        txtTeh = new javax.swing.JTextField();
        cbKopiSusu = new javax.swing.JComboBox<>();
        cbMilo = new javax.swing.JComboBox<>();
        cbTeh = new javax.swing.JComboBox<>();
        txtTotalKopiSusu = new javax.swing.JTextField();
        txtTotalMilo = new javax.swing.JTextField();
        txtTotalTeh = new javax.swing.JTextField();
        btnTotalHarga = new javax.swing.JButton();
        txtTotalMinuman = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("PILIHAN MENU MINUMAN");

        ckbKopiSusu.setText("Kopi Susu");
        ckbKopiSusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbKopiSusuActionPerformed(evt);
            }
        });

        ckbMilo.setText("Milo");
        ckbMilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMiloActionPerformed(evt);
            }
        });

        ckbTeh.setText("Teh");
        ckbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTehActionPerformed(evt);
            }
        });

        txtKopiSusu.setText("0");

        txtMilo.setText("0");

        txtTeh.setText("0");

        cbKopiSusu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbKopiSusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKopiSusuActionPerformed(evt);
            }
        });

        cbMilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbMilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMiloActionPerformed(evt);
            }
        });

        cbTeh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cbTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTehActionPerformed(evt);
            }
        });

        txtTotalKopiSusu.setText("0");

        txtTotalMilo.setText("0");

        txtTotalTeh.setText("0");

        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        txtTotalMinuman.setText("0");
        txtTotalMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMinumanActionPerformed(evt);
            }
        });

        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKembali)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbKopiSusu)
                            .addComponent(ckbMilo)
                            .addComponent(ckbTeh))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtKopiSusu, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(txtMilo)
                                    .addComponent(txtTeh))
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMilo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTeh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbKopiSusu, 0, 117, Short.MAX_VALUE)
                                    .addComponent(btnTotalHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalKopiSusu)
                            .addComponent(txtTotalMilo)
                            .addComponent(txtTotalTeh)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbKopiSusu)
                    .addComponent(txtKopiSusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKopiSusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalKopiSusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMilo)
                    .addComponent(txtMilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbTeh)
                    .addComponent(txtTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalHarga)
                    .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(btnKembali)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMinumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMinumanActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMinuman.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void ckbKopiSusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbKopiSusuActionPerformed
        txtKopiSusu.setText("16000");
    }//GEN-LAST:event_ckbKopiSusuActionPerformed

    private void ckbMiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMiloActionPerformed
        txtMilo.setText("7000");
    }//GEN-LAST:event_ckbMiloActionPerformed

    private void ckbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTehActionPerformed
        txtTeh.setText("7000");
    }//GEN-LAST:event_ckbTehActionPerformed

    private void cbKopiSusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiSusuActionPerformed
        int jumlah = (int)cbKopiSusu.getSelectedIndex();
        double harga = Double.parseDouble(txtKopiSusu.getText());
        double total = jumlah * harga;
        txtTotalKopiSusu.setText(Double.toString(total));
    }//GEN-LAST:event_cbKopiSusuActionPerformed

    private void cbMiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMiloActionPerformed
        int jumlah = (int)cbMilo.getSelectedIndex();
        double harga = Double.parseDouble(txtMilo.getText());
        double total = jumlah * harga;
        txtTotalMilo.setText(Double.toString(total));
    }//GEN-LAST:event_cbMiloActionPerformed

    private void cbTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehActionPerformed
        int jumlah = (int)cbTeh.getSelectedIndex();
        double harga = Double.parseDouble(txtTeh.getText());
        double total = jumlah * harga;
        txtTotalTeh.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        double a = Double.parseDouble(txtTotalKopiSusu.getText());
        double b = Double.parseDouble(txtTotalMilo.getText());
        double c = Double.parseDouble(txtTotalTeh.getText());
        double total = a+b+c;
        txtTotalMinuman.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMinuman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMinuman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbKopiSusu;
    private javax.swing.JComboBox<String> cbMilo;
    private javax.swing.JComboBox<String> cbTeh;
    private javax.swing.JCheckBox ckbKopiSusu;
    private javax.swing.JCheckBox ckbMilo;
    private javax.swing.JCheckBox ckbTeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtKopiSusu;
    private javax.swing.JTextField txtMilo;
    private javax.swing.JTextField txtTeh;
    private javax.swing.JTextField txtTotalKopiSusu;
    private javax.swing.JTextField txtTotalMilo;
    private javax.swing.JTextField txtTotalMinuman;
    private javax.swing.JTextField txtTotalTeh;
    // End of variables declaration//GEN-END:variables
}
