/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum29062026;



public class FormMakanan extends javax.swing.JFrame {

    /**
     * Creates new form FormMakanan
     */
    private FormUtama utama;
            
    public FormMakanan() {
        initComponents();
    }

    public FormMakanan(FormUtama utama) {
        this.utama = utama;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        ckbMieAyam = new javax.swing.JCheckBox();
        ckbMiePiai = new javax.swing.JCheckBox();
        ckbSoto = new javax.swing.JCheckBox();
        txtMieAyam = new javax.swing.JTextField();
        txtMiePiai = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        cbMieAyam = new javax.swing.JComboBox<>();
        cbMiePiai = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        txtTotalMieAyam = new javax.swing.JTextField();
        txtTotalMiePiai = new javax.swing.JTextField();
        txtTotalSoto = new javax.swing.JTextField();
        txtTotalMakanan = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnTotalHarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("PILIHAN MENU MAKANAN");

        ckbMieAyam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbMieAyam.setText("Mie Ayam");
        ckbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMieAyamActionPerformed(evt);
            }
        });

        ckbMiePiai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbMiePiai.setText("Mie Piai");
        ckbMiePiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMiePiaiActionPerformed(evt);
            }
        });

        ckbSoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckbSoto.setText("Soto");
        ckbSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSotoActionPerformed(evt);
            }
        });

        txtMieAyam.setText("0");
        txtMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMieAyamActionPerformed(evt);
            }
        });

        txtMiePiai.setText("0");

        txtSoto.setText("0");

        cbMieAyam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMieAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMieAyamActionPerformed(evt);
            }
        });

        cbMiePiai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbMiePiai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMiePiaiActionPerformed(evt);
            }
        });

        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jumlah", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSotoActionPerformed(evt);
            }
        });

        txtTotalMieAyam.setText("0");

        txtTotalMiePiai.setText("0");

        txtTotalSoto.setText("0");

        txtTotalMakanan.setText("0");

        btnKembali.setText("KEMBALI");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ckbMiePiai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ckbMieAyam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ckbSoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMieAyam, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(txtMiePiai)
                                    .addComponent(txtSoto))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbMiePiai, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTotalHarga)
                                .addGap(66, 66, 66)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalMieAyam, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(txtTotalMiePiai)
                            .addComponent(txtTotalSoto)
                            .addComponent(txtTotalMakanan))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMieAyam)
                    .addComponent(txtMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMieAyam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMiePiai)
                    .addComponent(txtMiePiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMiePiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalMiePiai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMieAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMieAyamActionPerformed

    private void ckbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMieAyamActionPerformed
        txtMieAyam.setText("15000");
    }//GEN-LAST:event_ckbMieAyamActionPerformed

    private void ckbMiePiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMiePiaiActionPerformed
        txtMiePiai.setText("11000");
    }//GEN-LAST:event_ckbMiePiaiActionPerformed

    private void ckbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSotoActionPerformed
        txtSoto.setText("12000");
    }//GEN-LAST:event_ckbSotoActionPerformed

    private void cbMieAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMieAyamActionPerformed
        int jumlah = (int)cbMieAyam.getSelectedIndex();
        double harga = Double.parseDouble(txtMieAyam.getText());
        double total = jumlah * harga;
        txtTotalMieAyam.setText(Double.toString(total));
    }//GEN-LAST:event_cbMieAyamActionPerformed

    private void cbMiePiaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMiePiaiActionPerformed
       int jumlah = (int)cbMiePiai.getSelectedIndex();
       double harga = Double.parseDouble(txtMiePiai.getText());
       double total = jumlah * harga;
       txtTotalMiePiai.setText(Double.toString(total));
    }//GEN-LAST:event_cbMiePiaiActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
        int jumlah = (int)cbSoto.getSelectedIndex();
        double harga = Double.parseDouble(txtSoto.getText());
        double total = jumlah * harga;
        txtTotalSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        double a = Double.parseDouble(txtTotalMieAyam.getText());
        double b = Double.parseDouble(txtTotalMiePiai.getText());
        double c = Double.parseDouble(txtTotalSoto.getText());
        double total = a+b+c;
        txtTotalMakanan.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotalMakanan.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JComboBox<String> cbMieAyam;
    private javax.swing.JComboBox<String> cbMiePiai;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox ckbMieAyam;
    private javax.swing.JCheckBox ckbMiePiai;
    private javax.swing.JCheckBox ckbSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField txtMieAyam;
    private javax.swing.JTextField txtMiePiai;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotalMakanan;
    private javax.swing.JTextField txtTotalMieAyam;
    private javax.swing.JTextField txtTotalMiePiai;
    private javax.swing.JTextField txtTotalSoto;
    // End of variables declaration//GEN-END:variables
}
