/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Praktikum29062026;

/**
 *
 * @author USER
 */
public class FormUtama extends javax.swing.JFrame {

    /**
     * Creates new form FormUtama
     */
    
    private FormUtama utama;
    
    public FormUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMakanan = new javax.swing.JButton();
        btnMinuman = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();
        lblNo = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNo = new javax.swing.JTextField();
        lblHargaMakan = new javax.swing.JLabel();
        lblHargaMinum = new javax.swing.JLabel();
        txtTotalMakanan = new javax.swing.JTextField();
        txtTotalMinuman = new javax.swing.JTextField();
        txtTotalHarga = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnTotalHarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("FORM PEMESANAN MAKANAN");

        btnMakanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMakanan.setText("Menu Makanan");
        btnMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakananActionPerformed(evt);
            }
        });

        btnMinuman.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMinuman.setText("Menu Minuman");
        btnMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinumanActionPerformed(evt);
            }
        });

        lblNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNama.setText("Nama Pelanggan");

        lblNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNo.setText("No. Meja");

        lblHargaMakan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHargaMakan.setText("Total Harga Makanan");

        lblHargaMinum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHargaMinum.setText("Total Harga Minuman");

        txtTotalMakanan.setText("0");
        txtTotalMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalMakananActionPerformed(evt);
            }
        });

        txtTotalMinuman.setText("0");

        txtTotalHarga.setText("0");

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTotalHarga.setText("Total Harga");
        btnTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMakanan)
                            .addComponent(btnMinuman)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNo, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(txtNama))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHargaMakan)
                                .addGap(55, 55, 55)
                                .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblHargaMinum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalMinuman)
                                    .addComponent(txtTotalHarga)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(151, 151, 151)))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(35, 35, 35)
                .addComponent(btnExit)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHargaMakan)
                            .addComponent(txtTotalMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNo)
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99)
                        .addComponent(btnMakanan)
                        .addGap(30, 30, 30)
                        .addComponent(btnMinuman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExit)
                            .addComponent(btnReset))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHargaMinum)
                            .addComponent(txtTotalMinuman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTotalHarga)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(203, 203, 203))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakananActionPerformed
        FormMakanan frm = new FormMakanan(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMakananActionPerformed

    public void setTotalMakanan(String nilai){
        txtTotalMakanan.setText(nilai);
    }
    private void txtTotalMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalMakananActionPerformed

    private void btnMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumanActionPerformed
        FormMinuman frm = new FormMinuman(this);
        frm.setVisible(true);
    }//GEN-LAST:event_btnMinumanActionPerformed

    private void btnTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalHargaActionPerformed
        if (txtNama.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Nama pelanggan belum diisi!",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        txtNama.requestFocus();
        return;
        }

        if (txtNo.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Nomor meja belum diisi!",
                "Peringatan",
                javax.swing.JOptionPane.WARNING_MESSAGE);
        txtNo.requestFocus();
        return;
        }
        
        double makanan = Double.parseDouble(txtTotalMakanan.getText());
        double minuman = Double.parseDouble(txtTotalMinuman.getText());
        double total = makanan + minuman;

        txtTotalHarga.setText(String.valueOf(total));

        String pesan =
            "========== STRUK PEMESANAN ==========\n" +
            "Nama Pelanggan : " + txtNama.getText() + "\n" +
            "No. Meja       : " + txtNo.getText() + "\n\n" +
            "Total Makanan  : Rp " + txtTotalMakanan.getText() + "\n" +
            "Total Minuman  : Rp " + txtTotalMinuman.getText() + "\n" +
            "--------------------------------------\n" +
            "TOTAL BAYAR    : Rp " + txtTotalHarga.getText();

            javax.swing.JOptionPane.showMessageDialog(this,pesan,"Detail Pesanan",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);


    }//GEN-LAST:event_btnTotalHargaActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtNama.setText("");
        txtNo.setText("");
        txtTotalMakanan.setText("0");
        txtTotalMinuman.setText("0");
        txtTotalHarga.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed
    public void setTotalMinuman(String nilai){
        txtTotalMinuman.setText(nilai);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMakanan;
    private javax.swing.JButton btnMinuman;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotalHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHargaMakan;
    private javax.swing.JLabel lblHargaMinum;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNo;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtTotalMakanan;
    private javax.swing.JTextField txtTotalMinuman;
    // End of variables declaration//GEN-END:variables
}
